version = "3.8.6"
runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.significant = 2

# Scala 3 specific rewrites
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.insertEndMarkerMinLines = 30
rewrite.scala3.countEndMarkerLines = lastBlockOnly

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]

align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.source = keep
